name: CI/CD Pipeline for Backend Erklika Pro

on:
  push:
    branches:
      - master  # Jalankan hanya saat ada perubahan di branch "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy the application to the VPS
      - name: Deploy to GCP
        run: |
          sshpass -p "${{ secrets.GCP_PASSWORD_STAGING }}" ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_USER_STAGING }} << 'EOF'


            cd skripsi/fe
            git restore package-lock.json
            git pull origin master
            npm install

            export NEXT_PUBLIC_ENV_BACKEND_URL=${{ secrets.NEXT_PUBLIC_ENV_BACKEND_URL }} 
            export ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }} 

            npm run build
            pm2 restart skripsi-fe --update-env

            # Save PM2 process list
            pm2 save
          EOF
